root = "."
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./api.bin"
  cmd = "make api-build"
  post_cmd = []
  pre_cmd = []
  delay = 10000
  exclude_dir = ["readme", "scripts", "deployments", "docs", "migrations", "out", "cmd/docs", "node_modules", "./internal/view/static/js"]
  exclude_file = [".gitignore", ".dockerignore", "*.md", "LICENSE"]
  exclude_regex = ["_test.go", ".dockerfile", "_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "templ", "ts"]
  include_file = []
  kill_delay = "0s"
  log = "air.log"
  poll = false
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = true

[proxy]
  app_port = 23450
  enabled = true
  proxy_port = 23460

[screen]
  clear_on_rebuild = false
  keep_scroll = true
