app:
  dockerfile: api.test.dockerfile
  build_context: ../
  app_config: /build/config/api.yaml
  admin_user: admin
  admin_password: admin
  host: localhost
  port: 23450
  # external_data_source: true
  external: true