DROP TRIGGER IF EXISTS author_created_before_grant ON author;
DROP FUNCTION IF EXISTS check_user_created_before_grant;
DROP TABLE IF EXISTS plant_album;
DROP TABLE IF EXISTS album;
DROP TABLE IF EXISTS post_tag;
DROP TABLE IF EXISTS plant_post;
DROP TABLE IF EXISTS post_photo;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS plant_photo;
DROP TABLE IF EXISTS plant;
DROP TABLE IF EXISTS plant_category;
DROP TABLE IF EXISTS "file";
DROP TABLE IF EXISTS author;
DROP TABLE IF EXISTS app_user;
