database:
name: example_value
user: example_value
password: your_password_here
host: example.com
port: 8080
max_connections: 12345
max_conn_life_time: example_value
hasher:
hash_cost: 12345

api:
urlprefix: https://example.com/path
port: 8080
static: example_value
media: example_value
media-storage: example_value


minio:
  post:
endpoint: example_value
user: example_value
password: your_password_here
bucket: example_value
  plant:
endpoint: example_value
user: example_value
password: your_password_here
bucket: example_value

fs:
root: example_value
  post:
bucket: example_value
  plant:
bucket: example_value

admins:
- login: example_value
password: your_password_here

auth:
session_expire_time: example_value

log:
console_level: example_value
file_level: example_value
dir: example_value
type: example_value
file_factory: example_value
file_type: example_value